os: linux
dist: focal

stages:
  - name: setup_and_run
  - name: wait_and_restart

jobs:
  include:
    - stage: setup_and_run
      script:
        - echo "Setting up environment..."
        - pip install telebot flask pymongo aiohttp python-telegram-bot motor
        - chmod +x *
        - echo "Running the compiled binary with travis_wait..."
        - travis_wait 360 bash -c "
            while true; do
              python3 ranbal.py || echo 'Application crashed. Restarting...';
              sleep 5;
            done"
      timeout: 360  # Timeout set for 6 hours (in minutes)
