pipelines:
  - name: Run Python Bot
    trigger_mode: ON_PUSH  
    ref_name: main          
    actions:

      # Install dependencies
      - action: "Install Dependencies"
        type: "BUILD"
        docker_image_name: "library/python"
        docker_image_tag: "3.10"
        execute_commands:
          - python -m pip install --upgrade pip
          - pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot motor
          - chmod +x bgmi  # Grant execution permission

      # Run the bot
      - action: "Run Bot"
        type: "BUILD"
        docker_image_name: "library/python"
        docker_image_tag: "3.10"
        execute_commands:
          - chmod +x bgmi  # Ensure execution permission before running
          - python ranbal.py
